[package]
name = "ngrammatic"
version = "0.1.0"
authors = ["Will Page <compenguy@gmail.com>"]
description = "Character-oriented ngram generator and fuzzy matching library."
documentation = ""
homepage = "https://github.com/compenguy/ngrammatic"
repository = "https://github.com/compenguy/ngrammatic"
readme = "README.md"
categories = ["text-processing"]
keywords = ["fuzzy", "ngrams", "shingles"]
license = "MIT"

[lib]
name = "ngrammatic"

[dependencies]

[features]
default = ["case_insensitive_ngrams"]

case_insensitive_ngrams = []
